//
//  HitsModel.swift
//  AppleMusicSwiftUI
//
//  Created by Ilya Volkov on 13.05.2022.
//

struct HitsModel {
    static func createModel() -> [CategorySection] {
        return [
            CategorySection(sectionTitle: nil, cells: [
                CategoryCell(title: Strings.onlyHitsCellTitel,
                             producerTitle: Strings.appleMusicHitsProducerTitle,
                             cover: Icons.onlyHits2Icon),
                CategoryCell(title: Strings.goldenSupplyCellTitle,
                             producerTitle: Strings.appleMusicPopProducerTitle,
                             cover: Icons.goldReserveIcon),
                CategoryCell(title: Strings.acousticHitsCellTitle,
                             producerTitle: Strings.appleMusicPopProducerTitle,
                             cover: Icons.acousticHits2Icon),
                CategoryCell(title: Strings.futureHitsCellTitle,
                             producerTitle: Strings.appleMusicProducerTitle,
                             cover: Icons.futureHits2Icon)]),
            
            CategorySection(sectionTitle: Strings.playlistsSectionTitle, cells: [
                CategoryCell(title: Strings.hitsPlanetTitle,
                             producerTitle: Strings.appleMusicHitsProducerTitle,
                             cover: Icons.hitsPlanetIcon),
                CategoryCell(title: Strings.nostalgiaForRussianHitsTitle,
                             producerTitle: Strings.appleMusicHitsInRussianProducerTitle,
                             cover: Icons.nostalgiaRussianHitsIcon),
                CategoryCell(title: Strings.crestTitle,
                             producerTitle: Strings.appleMusicHitsInRussianProducerTitle,
                             cover: Icons.onTheCrestIcon),
                CategoryCell(title: Strings.nativeSongsTitle,
                             producerTitle: Strings.appleMusicHitsInRussianProducerTitle,
                             cover: Icons.nativeSongsIcon),
                CategoryCell(title: Strings.onlyHitsCellTitel,
                             producerTitle: Strings.appleMusicHitsProducerTitle,
                             cover: Icons.onlyHitsIcon),
                CategoryCell(title: Strings.lifeIsBeautifulTitle,
                             producerTitle: Strings.appleMusicPopProducerTitle,
                             cover: Icons.lifeIsBeautifulIcon),
                CategoryCell(title: Strings.nostalgiaForTheOldStageTitle,
                             producerTitle: Strings.appleMusicProducerTitle,
                             cover: Icons.nostalgiaOldIcon),
                CategoryCell(title: Strings.lightHitsTitle,
                             producerTitle: Strings.appleMusicPopProducerTitle,
                             cover: Icons.lightHitsIcon),
                CategoryCell(title: Strings.teenPopHitsTitle,
                             producerTitle: " ",
                             cover: Icons.tinPopHitsIcon),
                CategoryCell(title: Strings.futureHitsCellTitle,
                             producerTitle: Strings.appleMusicProducerTitle,
                             cover: Icons.futureHitsIcon),
                CategoryCell(title: Strings.drakeEffectTitle,
                             producerTitle: Strings.appleMusicHipHopProducerTitle,
                             cover: Icons.drakeEffectIcon),
                CategoryCell(title: Strings.popMusicNoveltiesCellTitle,
                             producerTitle: Strings.appleMusicPopProducerTitle,
                             cover: Icons.rectanglePopNoveltiesIcon),
                CategoryCell(title: Strings.noWorriesTitle,
                             producerTitle: Strings.appleMusicHitsProducerTitle,
                             cover: Icons.noWorriesIcon),
                CategoryCell(title: Strings.acousticHitsCellTitle,
                             producerTitle: Strings.appleMusicPopProducerTitle,
                             cover: Icons.acousticHitsIcon),
                CategoryCell(title: Strings.rbHitsTitle,
                             producerTitle: Strings.appleMusicRBProducerTitle,
                             cover: Icons.rbHitsIcon)]),
            
            CategorySection(sectionTitle: Strings.hotTracksSectionTitle, cells: [
                CategoryCell(title: Strings.harmonyTitle,
                             producerTitle: Strings.artikAstiProducerTitle,
                             cover: Icons.harmonyIcon),
                CategoryCell(title: Strings.lettingGoTitle,
                             producerTitle: Strings.egorCreedMaksimProducerTitle,
                             cover: Icons.lettingGoIcon),
                CategoryCell(title: Strings.phoenixTitle,
                             producerTitle: Strings.annaAstiProducerTitle,
                             cover: Icons.phoenixIcon),
                CategoryCell(title: Strings.sunOfMonacoTitle,
                             producerTitle: Strings.lucaCHebotinaProducerTitle,
                             cover: Icons.sunInMonacoIcon),
                CategoryCell(title: Strings.birdTitle,
                             producerTitle: Strings.hammaliNavaiProducerTitle,
                             cover: Icons.birdIcon),
                CategoryCell(title: Strings.sacrificeTitle,
                             producerTitle: Strings.theWeekndProducerTitle,
                             cover: Icons.sacrificeIcon),
                CategoryCell(title: Strings.veneraFloodlightTitle,
                             producerTitle: Strings.vanyaDmitrienkoProducerTitle,
                             cover: Icons.veneraFloodLightIcon),
                CategoryCell(title: Strings.shineTitle,
                             producerTitle: Strings.ramilProducerTitle,
                             cover: Icons.shineIcon),
                CategoryCell(title: Strings.astonautInTheOceanTitle,
                             producerTitle: Strings.maskedWolfProducerTitle,
                             cover: Icons.austonautIcon),
                CategoryCell(title: Strings.imInMomentTitle,
                             producerTitle: Strings.jarahovMarkulProducerTitle,
                             cover: Icons.imInMomentIcon),
                CategoryCell(title: Strings.minorTitle,
                             producerTitle: Strings.miyagiProducerTitle,
                             cover: Icons.minorIcon),
                CategoryCell(title: Strings.bulletTitle,
                             producerTitle: Strings.miyagiProducerTitle,
                             cover: Icons.bulletIcon)]),
            
            CategorySection(sectionTitle: Strings.newReleasesSectionTitle, cells: [
                CategoryCell(title: Strings.voyageTitle,
                             producerTitle: Strings.abbaProducerTitle,
                             cover: Icons.abbaIcon),
                CategoryCell(title: Strings.itllAllMakeSenseTitle,
                             producerTitle: Strings.jamesArthurProducerTitle,
                             cover: Icons.itAllMakeSenseIcon),
                CategoryCell(title: Strings.stillOverItTitle,
                             producerTitle: Strings.summerWalkerProducerTitle,
                             cover: Icons.stillOverItIcon),
                CategoryCell(title: Strings.alikeTitle,
                             producerTitle: Strings.edSheeranProducerTitle,
                             cover: Icons.edSheeranIcon),
                CategoryCell(title: Strings.lockdownSessionsTitle,
                             producerTitle: Strings.eltonJohnProducerTitle,
                             cover: Icons.eltonJohnIcon),
                CategoryCell(title: Strings.kidAMnesiaTitle,
                             producerTitle: Strings.radioheadProducerTitle,
                             cover: Icons.kidAMnistiaIcon),
                CategoryCell(title: Strings.valentineTitle,
                             producerTitle: Strings.snailMailProducerTitle,
                             cover: Icons.valentineIcon)]),
            
            CategorySection(sectionTitle: Strings.playlistByArtistSectionTitle, cells: [
                CategoryCell(title: Strings.mainTravisScottTitle,
                             producerTitle: Strings.appleMusicHipHopProducerTitle,
                             cover: Icons.travisScottGeneralIcon),
                CategoryCell(title: Strings.mainVideoTravisScottTitle,
                             producerTitle: Strings.appleMusicHipHopProducerTitle,
                             cover: Icons.travisScottGeneralVideoIcon),
                CategoryCell(title: Strings.mainDrakeTitle,
                             producerTitle: Strings.appleMusicHipHopProducerTitle,
                             cover: Icons.drakeGeneralIcon),
                CategoryCell(title: Strings.kanyeWestEssTitle,
                             producerTitle: Strings.radioProducerTitle,
                             cover: Icons.kanyeWestEssentialsIcon),
                CategoryCell(title: Strings.mainAbbaTitle,
                             producerTitle: Strings.appleMusicPopProducerTitle,
                             cover: Icons.abbaGeneralIcon),
                CategoryCell(title: Strings.mainTheWeekndTitle,
                             producerTitle: Strings.appleMusicRBProducerTitle,
                             cover: Icons.theWeekndGeneralIcon),
                CategoryCell(title: Strings.mainArianaGrandeTitle,
                             producerTitle: Strings.appleMusicPopProducerTitle,
                             cover: Icons.arianaGeneralIcon)]),
            
            CategorySection(sectionTitle: Strings.mainAlbumsSectionTitle, cells: [
                CategoryCell(title: Strings.hardAgeTitle,
                             producerTitle: Strings.maksimProducerTitle,
                             cover: Icons.hardAgeIcon),
                CategoryCell(title: Strings.biologyTitle,
                             producerTitle: Strings.viaGraProducerTitle,
                             cover: Icons.biologyIcon),
                CategoryCell(title: Strings.dooWopsTitle,
                             producerTitle: Strings.brunoMarsProducerTitle,
                             cover: Icons.dooWopsIcon),
                CategoryCell(title: Strings.noCeilingsTitle,
                             producerTitle: Strings.lilWayneTitle,
                             cover: Icons.noCeilingsIcon),
                CategoryCell(title: Strings.imOutTitle,
                             producerTitle: Strings.liymaProducerTitle,
                             cover: Icons.imOutIcon),
                CategoryCell(title: Strings.lemodaneTitle,
                             producerTitle: Strings.beyonceProducerTitle,
                             cover: Icons.lemonadeIcon)]),
            
            CategorySection(sectionTitle: Strings.favoriteArtistsSectionTitle, cells: [
                CategoryCell(title: Strings.justinBieberTitle,
                             producerTitle: nil,
                             cover: Icons.justinBieberCircleIcon),
                CategoryCell(title: Strings.zivertProducerTitle,
                             producerTitle: nil,
                             cover: Icons.zivertCircleIcon),
                CategoryCell(title: Strings.duaLipaTitle,
                             producerTitle: nil,
                             cover: Icons.duaLipaCircleIcon),
                CategoryCell(title: Strings.animalsTitle,
                             producerTitle: nil,
                             cover: Icons.animalsCircleIcon),
                CategoryCell(title: Strings.androProducerTitle,
                             producerTitle: nil,
                             cover: Icons.androCircleIcon),
                CategoryCell(title: Strings.hammaliTitle,
                             producerTitle: Strings.navaiTitle,
                             cover: Icons.navaiCircleIcon),
                CategoryCell(title: Strings.diploTitle,
                             producerTitle: nil,
                             cover: Icons.diploCircleIcon),
                CategoryCell(title: Strings.stTitle,
                             producerTitle: nil,
                             cover: Icons.stCircleIcon),
                CategoryCell(title: Strings.cinemaTitle,
                             producerTitle: nil,
                             cover: Icons.cinemaCircleIcon)])
        ]
    }
}
