//
//  LightPopModel.swift
//  AppleMusicSwiftUI
//
//  Created by Ilya Volkov on 11.05.2022.
//

struct LightPopModel {
    static func createModel() -> [CategorySection] {
        return [
            CategorySection(sectionTitle: nil, cells: [
                CategoryCell(title: "Сверхновая", producerTitle: "Сюзанна", cover: "suzanna"),
                CategoryCell(title: "Glitch Mode - The 2nd Album", producerTitle: "NCT DREAM", cover: "nct.dream"),
                CategoryCell(title: "Новинки поп-музыки", producerTitle: "Apple Music Поп", cover: "pop.novelties"),
                CategoryCell(title: "ПЕСНИ О ТВОИХ ГЛАЗАХ", producerTitle: "Akmal'", cover: "akmal"),
                CategoryCell(title: "ODDINARY", producerTitle: "Stray Kids", cover: "oddinary"),
                CategoryCell(title: "Поп-волна", producerTitle: "Apple Music Поп на русском", cover: "pop.wave")]),
            
            CategorySection(sectionTitle: "Пространственное звучание", cells: [
                CategoryCell(title: "PSY 9th", producerTitle: "PSY", cover: "psy9th"),
                CategoryCell(title: "Car Therapy Sessions - EP", producerTitle: "Faye Webster", cover: "faye.webster"),
                CategoryCell(title: "Forgiveness", producerTitle: "Girlpool", cover: "girlpool"),
                CategoryCell(title: "Do Me Dirty - Single", producerTitle: "Reece", cover: "reece"),
                CategoryCell(title: "MUNA", producerTitle: "MUNA", cover: "muna"),
                CategoryCell(title: "five seconds flat", producerTitle: "Lizzy McAlpine", cover: "lizzy.mcalpine"),
                CategoryCell(title: "Walangolo - Single", producerTitle: "DJ Neptune, Mr Eazi & Konshens", cover: "walangolo")]),
            
            CategorySection(sectionTitle: "Плейлисты", cells: [
                CategoryCell(title: "Новинки поп-музыки", producerTitle: "Apple Music Поп", cover: "rectangle.pop.novelties"),
                CategoryCell(title: "Поп-волна", producerTitle: "Apple Music Поп на русском", cover: "rectangle.pop.wave"),
                CategoryCell(title: "Пульс поп-музыки", producerTitle: "Apple Music Поп", cover: "pop.pulse"),
                CategoryCell(title: "Тренды поп-музыки", producerTitle: "Apple Music Поп", cover: "trends.pop.music"),
                CategoryCell(title: "Поп-карамель", producerTitle: "Apple Music Поп на русском", cover: "pop.karamel"),
                CategoryCell(title: "Красная дорожка", producerTitle: "Apple Music Поп на русском", cover: "red.road"),
                CategoryCell(title: "Новинки K-Pop", producerTitle: "Apple Music Поп", cover: "novelties.k.pop"),
                CategoryCell(title: "Танцпол", producerTitle: "Apple Music Танцевальная", cover: "dance"),
                CategoryCell(title: "Поп на русском для тренировки", producerTitle: "Apple Music Спорт", cover: "ru.pop.sport"),
                CategoryCell(title: "Семейные хиты", producerTitle: "Apple Music для семьи", cover: "family.hits"),
                CategoryCell(title: "Только хиты", producerTitle: "Apple Music Хиты", cover: "only.hits"),
                CategoryCell(title: "На гребне", producerTitle: "Apple Music Хиты на русском", cover: "on.the.crest"),
                CategoryCell(title: "Тин-поп-хиты", producerTitle: nil, cover: "tin.pop.hits"),
                CategoryCell(title: "Поп-музыка вне времени", producerTitle: "Apple Music Поп", cover: "out.of.time"),
                CategoryCell(title: "Ритмы и рифмы", producerTitle: "Apple Music", cover: "rhythm"),
                CategoryCell(title: "Восточная волна", producerTitle: "Apple Music", cover: "east.wave"),
                CategoryCell(title: "Будущие хиты", producerTitle: "Apple Music", cover: "future.hits"),
                CategoryCell(title: "Главные новинки", producerTitle: "Apple Music", cover: "general.novelties"),
                CategoryCell(title: "Up Next", producerTitle: "Apple Music Восход", cover: "up.next"),
                CategoryCell(title: "Легкие хиты", producerTitle: "Apple Music Поп", cover: "light.hits"),
                CategoryCell(title: "Без забот", producerTitle: "Apple Music Хиты", cover: "no.worries"),
                CategoryCell(title: "Только вечеринка", producerTitle: "Apple Music Вечеринка", cover: "only.party"),
                CategoryCell(title: "Тренировка под поп-хиты", producerTitle: "Apple Music Поп", cover: "sport.pop.hits"),
                CategoryCell(title: "Акустические хиты", producerTitle: "Apple Music Поп", cover: "acoustic.hits"),
                CategoryCell(title: "Пятница!", producerTitle: "Apple Music Поп", cover: "friday"),
                CategoryCell(title: "Безмятежные дни", producerTitle: "Apple Music Поп", cover: "halcyon.days"),
                CategoryCell(title: "Планета поп-музыки", producerTitle: "Apple Music Поп", cover: "hits.planet"),
                CategoryCell(title: "Прощай, любовь", producerTitle: "Apple Music Поп", cover: "goodbye.love"),
                CategoryCell(title: "Жизнь прекрасна", producerTitle: "Apple Music Поп", cover: "life.is.beautiful"),
                CategoryCell(title: "Ностальгия по поп-латино 2000-х", producerTitle: nil, cover: "nostalgy"),
                CategoryCell(title: "Поп-делюкс", producerTitle: "Apple Music Поп", cover: "pop.delux")]),
            
            CategorySection(sectionTitle: "Горячие треки", cells: [
                CategoryCell(title: "iScream", producerTitle: "Deaton Chris Anthony & beabadoobee", cover: "iScream"),
                CategoryCell(title: "victim of nostalgia", producerTitle: "mxmtoon", cover: "mxmtoon"),
                CategoryCell(title: "graves", producerTitle: "Kind of Girl", cover: "graves"),
                CategoryCell(title: "Kind of Girl", producerTitle: "MUNA", cover: "muna"),
                CategoryCell(title: "Do me Dirty", producerTitle: "Reece", cover: "reece"),
                CategoryCell(title: "Things You Said", producerTitle: "gglum", cover: "gglum"),
                CategoryCell(title: "Spinning", producerTitle: "GRAE", cover: "spinning"),
                CategoryCell(title: "orange juice", producerTitle: "BETWEEN FRIENDS", cover: "orange.juice"),
                CategoryCell(title: "What a Lie", producerTitle: "Justine Skye", cover: "what.a.lie"),
                CategoryCell(title: "Love Like That (Words from Her)", producerTitle: "Suriel Hess", cover: "love.like.that"),
                CategoryCell(title: "El Vuelo", producerTitle: "Yarge", cover: "el.vuelo"),
                CategoryCell(title: "MUST BE NICE", producerTitle: "clide", cover: "must.be.nice"),
                CategoryCell(title: "Stangers", producerTitle: "Josie Dunne", cover: "strangers"),
                CategoryCell(title: "Autopilot", producerTitle: "Dev Lemons", cover: "autopilot"),
                CategoryCell(title: "Not That Girl", producerTitle: "Casey Baer", cover: "not.that.girl"),
                CategoryCell(title: "Beautiful Things (EMBRZ Remix)", producerTitle: "Brynn Elliott & EMBRZ", cover: "beautiful.things"),
                CategoryCell(title: "Bad Haircat (feat. JVKE)", producerTitle: "Stephanie Poerti", cover: "bad.haircut"),
                CategoryCell(title: "Cruel World", producerTitle: "Anna Sofia", cover: "cruel.world"),
                CategoryCell(title: "Getting Used To", producerTitle: "Addison Grace", cover: "getting.used.to")]),
            
            CategorySection(sectionTitle: "Новые релизы", cells: [
                CategoryCell(title: "Let's Say For Instance", producerTitle: "Emeli Sande", cover: "emeli.sande"),
                CategoryCell(title: "Old School", producerTitle: "Boyzlife", cover: "boyzlife"),
                CategoryCell(title: "Profound Mysteries", producerTitle: "Royksopp", cover: "royksopp"),
                CategoryCell(title: "Is It Comeback If I Never Left? - EP", producerTitle: "Ivory Layne", cover: "ivory.layne"),
                CategoryCell(title: "Everything I Didn't Say", producerTitle: "Ella Henderson", cover: "ella.henderson"),
                CategoryCell(title: "Apple Music Home Session: Emeli Sande - Single", producerTitle: "Emeli Sande", cover: "emeli.sande2"),
                CategoryCell(title: "No Romeo - EP", producerTitle: "Dylan", cover: "dylan"),
                CategoryCell(title: "Hope Is a Drug", producerTitle: "Charlie Simpson", cover: "charlie.simpson")]),
            
            CategorySection(sectionTitle: "Избранные альбомы и интервью", cells: [
                CategoryCell(title: "КРИОЛИТ", producerTitle: "NILETTO", cover: "niletto"),
                CategoryCell(title: "30", producerTitle: "Adele", cover: "adele"),
                CategoryCell(title: "JANI GIPSY", producerTitle: "Andro", cover: "andro"),
                CategoryCell(title: "Voyage", producerTitle: "ABBA", cover: "abba"),
                CategoryCell(title: "=", producerTitle: "Ed Sheeran", cover: "ed.sheeran"),
                CategoryCell(title: "Music of the Spheres", producerTitle: "Coldplay", cover: "coldplay"),
                CategoryCell(title: "The Lockdown Sessions", producerTitle: "Elton John", cover: "elton.john"),
                CategoryCell(title: "Sense of Human", producerTitle: "Markul", cover: "markul"),
                CategoryCell(title: "Friends That Break Your Heart", producerTitle: "James Blake", cover: "james.blake"),
                CategoryCell(title: "Vynil #2", producerTitle: "Zivert", cover: "zivert"),
                CategoryCell(title: "MONTERO", producerTitle: "Lil Nas X", cover: "lil.nas.x"),
                CategoryCell(title: "Katana", producerTitle: "Ramil'", cover: "katana"),
                CategoryCell(title: "JOSE", producerTitle: "J Balvin", cover: "j.balvin"),
                CategoryCell(title: "Агапэ", producerTitle: "Дидар", cover: "didar"),
                CategoryCell(title: "Mercury - Act 1", producerTitle: "Imagine Dragons", cover: "mercury.act1"),
                CategoryCell(title: "Миллениум X", producerTitle: "Artik & Asti", cover: "artik.asti"),
                CategoryCell(title: "If I Can't Have Love, I Want Power", producerTitle: "Halsey", cover: "halsey"),
                CategoryCell(title: "Когда хорошему человеку плохо", producerTitle: "HammaAli & Navai", cover: "navai"),
                CategoryCell(title: "Human (Deluxe)", producerTitle: "OneRepublic", cover: "one.republic"),
                CategoryCell(title: "ПОГОДА ЛЮБИТЬ", producerTitle: "просто Лера", cover: "prosto.lera"),
                CategoryCell(title: "Happier Than Ever", producerTitle: "Billie Eilish", cover: "billie"),
                CategoryCell(title: "Мудрец", producerTitle: "Jah Khalib", cover: "mudrez"),
                CategoryCell(title: "Welcome to the Madhouse", producerTitle: "Tones And I", cover: "tones.and.i"),
                CategoryCell(title: "ЙАЙ", producerTitle: "FEDUK", cover: "feduk"),
                CategoryCell(title: "Dancing With The Devil", producerTitle: "Demi Lovato", cover: "demi.lovato"),
                CategoryCell(title: "Декоративно-прикладное искусство", producerTitle: "Монеточка", cover: "monetochka"),
                CategoryCell(title: "Chemtrails Over the Country Club", producerTitle: "Lana Del Rey", cover: "lana.del.rey"),
                CategoryCell(title: "Когда были волны", producerTitle: "Сестры", cover: "sisters"),
                CategoryCell(title: "Bang - EP", producerTitle: "Rita Ora & Imanbek", cover: "bang.ep"),
                CategoryCell(title: "22", producerTitle: "Эрика Лундмоен", cover: "22"),
                CategoryCell(title: "Spaceman", producerTitle: "Nick Jonas", cover: "spaceman"),
                CategoryCell(title: "Интергалактик", producerTitle: "Cream Soda", cover: "cream.soda")]),
            
            CategorySection(sectionTitle: "Плейлист по артистам", cells: [
                CategoryCell(title: "Гарри Стайлз: главное", producerTitle: "Apple Music Поп", cover: "general.garry"),
                CategoryCell(title: "Lizzo: главное", producerTitle: "Apple Music Поп", cover: "general.lizzo"),
                CategoryCell(title: "Джастин Бибер: главное", producerTitle: "Apple Music Поп", cover: "general.bieber"),
                CategoryCell(title: "Bad Bunny: главное", producerTitle: "Apple Music Урбан-латино", cover: "general.bad.bunny"),
                CategoryCell(title: "WILLOW: главное", producerTitle: "Apple Music", cover: "general.willow"),
                CategoryCell(title: "Ava Max: главное", producerTitle: "Apple Music Поп", cover: "general.ava.max"),
                CategoryCell(title: "Jack Harlow Essentials", producerTitle: "Apple Music", cover: "general.jackharlow"),
                CategoryCell(title: "Дуа Липа: главное", producerTitle: "Apple Music Поп", cover: "general.dua.lipa"),
                CategoryCell(title: "Frank Ocean: главное", producerTitle: "Apple Music R&B", cover: "general.frank.ocean"),
                CategoryCell(title: "Сэм Смит: главное", producerTitle: "Apple Music Поп", cover: "general.sam.smith"),
                CategoryCell(title: "Tove Lo: главное", producerTitle: "Apple Music Поп", cover: "general.tove.lo"),
                CategoryCell(title: "Marshmello: главное", producerTitle: " ", cover: "general.mashmallow"),
                CategoryCell(title: "Machine Gun Kelly: главное", producerTitle: "Apple Music Хип-хоп", cover: "general.mgk"),
                CategoryCell(title: "Карли Рэй Джепсен: главное", producerTitle: "Apple Music Поп", cover: "general.karly.ray"),
                CategoryCell(title: "Мэйси Питерс: главное", producerTitle: "Apple Music", cover: "general.piters"),
                CategoryCell(title: "Джоэл Корри: главное", producerTitle: "Apple Music Танцевальная", cover: "general.joel")]),
            
            CategorySection(sectionTitle: "Видеоплейлисты", cells: [
                CategoryCell(title: "Главные видеоновинки", producerTitle: "Apple Music", cover: "general.video"),
                CategoryCell(title: "Только видеохиты", producerTitle: "Apple Music Поп", cover: "only.videohits"),
                CategoryCell(title: "Поп-музыка: видео", producerTitle: "Apple Music Поп", cover: "video.pop.music"),
                CategoryCell(title: "Нельзя пропустить", producerTitle: "Apple Music Поп", cover: "video."),
                CategoryCell(title: "Новаторские видео", producerTitle: "Apple Music Поп", cover: "innovative.videos"),
                CategoryCell(title: "Видео для вечеринки", producerTitle: "Apple Music Поп", cover: "video.for.party"),
                CategoryCell(title: "Классические анимированные видео", producerTitle: "Apple Music Поп", cover: "classic.anime"),
                CategoryCell(title: "Видеоманифесты", producerTitle: "Apple Music Поп", cover: "video.manifests"),
                CategoryCell(title: "Классические танцевальные движения: видео", producerTitle: "Apple Music Поп", cover: "classic.dancing"),
                CategoryCell(title: "Лучшие живые выступления", producerTitle: "Apple Music Поп", cover: "best.live"),
                CategoryCell(title: "Видео, опередившие моду", producerTitle: "Apple Music Поп", cover: "ahead.of.time"),
                CategoryCell(title: "Классические видео со знаменитостями", producerTitle: "Apple Music Поп", cover: "classic.video")]),
            
            CategorySection(sectionTitle: "Видео", cells: [
                CategoryCell(title: "No One Dies From Love", producerTitle: "Tove Lo", cover: "video.tove.lo"),
                CategoryCell(title: "SURPRISE", producerTitle: "CHAI", cover: "video.surprise"),
                CategoryCell(title: "See You Soon", producerTitle: "baebadoobee", cover: "video.beabadoobee"),
                CategoryCell(title: "ay!", producerTitle: "Machine Gun Kelly & Lil Wayne", cover: "video.mgk")]),
            
            CategorySection(sectionTitle: "Наши любимые артисты", cells: [
                CategoryCell(title: "Harry Styles", producerTitle: nil, cover: "harry.styles"),
                CategoryCell(title: "Lizzo", producerTitle: nil, cover: "lizzo"),
                CategoryCell(title: "Ava Max", producerTitle: nil, cover: "ava.max"),
                CategoryCell(title: "Post Malone", producerTitle: nil, cover: "post.malone"),
                CategoryCell(title: "The Kid LAROI", producerTitle: nil, cover: "the.kid.laroi"),
                CategoryCell(title: "Justin Bieber", producerTitle: nil, cover: "jastin.bieber"),
                CategoryCell(title: "Noah Cyrus", producerTitle: nil, cover: "noah.cyrus"),
                CategoryCell(title: "Rihanna", producerTitle: nil, cover: "rihanna"),
                CategoryCell(title: "Lizzy McAlpine", producerTitle: nil, cover: "lizzy.cirlce"),
                CategoryCell(title: "Khalid", producerTitle: nil, cover: "khalid"),
                CategoryCell(title: "Remi Wolf", producerTitle: nil, cover: "remi.wolf"),
                CategoryCell(title: "Doja Cat", producerTitle: nil, cover: "doja.cat"),
                CategoryCell(title: "ELIO", producerTitle: nil, cover: "elio"),
                CategoryCell(title: "Dua Lipa", producerTitle: nil, cover: "dua.lipa"),
                CategoryCell(title: "GAYLE", producerTitle: nil, cover: "gayle")])
        ]
    }
}
