//
//  SmoothJazzModel.swift
//  AppleMusicSwiftUI
//
//  Created by Ilya Volkov on 15.05.2022.
//

struct SmoothJazzModel {
    static func createModel() -> [CategorySection] {
        return [
            CategorySection(sectionTitle: nil, cells: [
                CategoryCell(title: Strings.pureJazzCellTitle,
                             producerTitle: Strings.appleMusicJazzProducerTitle,
                             cover: Icons.pureJazzRectangleIcon),
                CategoryCell(title: Strings.theChopinProjectTitle,
                             producerTitle: Strings.kurtRosenwinkelProducerTitle,
                             cover: Icons.theChopinRectangleIcon),
                CategoryCell(title: Strings.blackRadio3Title,
                             producerTitle: Strings.robertGlasperProducerTitle,
                             cover: Icons.blackRadioRectangleIcon)]),
            
            CategorySection(sectionTitle: Strings.playlistsSectionTitle, cells: [
                CategoryCell(title: Strings.relaxJazzCellTitle,
                             producerTitle: Strings.appleMusicJazzProducerTitle,
                             cover: Icons.relaxJazzIcon),
                CategoryCell(title: Strings.manySidedJazzTitle,
                             producerTitle: Strings.appleMusicJazzProducerTitle,
                             cover: Icons.manySidedJazzIcon),
                CategoryCell(title: Strings.nduduzoTitle,
                             producerTitle: Strings.appleMusicAfricaProducerTitle,
                             cover: Icons.nduduzoIcon),
                CategoryCell(title: Strings.barWithPianoTitle,
                             producerTitle: Strings.appleMusicJazzProducerTitle,
                             cover: Icons.barWithPianoIcon),
                CategoryCell(title: Strings.actualJazzCellTitle,
                             producerTitle: Strings.appleMusicJazzProducerTitle,
                             cover: Icons.actualJazzIcon),
                CategoryCell(title: Strings.intoxicationJazzTitle,
                             producerTitle: Strings.appleMusicJazzProducerTitle,
                             cover: Icons.intoxicationJazzIcon),
                CategoryCell(title: Strings.jazzCafeTitle,
                             producerTitle: Strings.appleMusicJazzProducerTitle,
                             cover: Icons.cafeJazzIcon),
                CategoryCell(title: Strings.pureJazzCellTitle,
                             producerTitle: Strings.appleMusicJazzProducerTitle,
                             cover: Icons.pureJazzSquareIcon)]),
            
            CategorySection(sectionTitle: Strings.hotTracksSectionTitle, cells: [
                CategoryCell(title: Strings.openChannelsTitle,
                             producerTitle: Strings.badBadNotGoodProducerTitle,
                             cover: Icons.openChannelsIcon),
                CategoryCell(title: Strings.periTitle,
                             producerTitle: Strings.bulutGulenProducerTitle,
                             cover: Icons.periIcon),
                CategoryCell(title: Strings.nouvelleEtudeTitle,
                             producerTitle: Strings.kurtRosenwinkelProducerTitle,
                             cover: Icons.nouvelleIcon),
                CategoryCell(title: Strings.nextStopTitle,
                             producerTitle: Strings.porticoQuartetProducerTitle,
                             cover: Icons.nextStopIcon),
                CategoryCell(title: Strings.prayerTitle,
                             producerTitle: Strings.joelRossProducerTitle,
                             cover: Icons.prayerIcon),
                CategoryCell(title: Strings.iLoveMusicTitle,
                             producerTitle: Strings.jeremyPeltProducerTitle,
                             cover: Icons.iLoveMusicIcon),
                CategoryCell(title: Strings.whyWeSpeakTitle,
                             producerTitle: Strings.robertGlasperProducerTitle,
                             cover: Icons.whyWeSpeakIcon),
                CategoryCell(title: Strings.hornetsTitle,
                             producerTitle: Strings.walterSmithProducerTitle,
                             cover: Icons.hornetsIcon)]),
            
            CategorySection(sectionTitle: Strings.liveMusicSectionTitle, cells: [
                CategoryCell(title: Strings.daveBrubeckTrioTitle,
                             producerTitle: Strings.daveBrubeckProducerTitle,
                             cover: Icons.daveBrubeckIcon),
                CategoryCell(title: Strings.aLoveSupremeTitle,
                             producerTitle: Strings.johnCalltrainProducerTitle,
                             cover: Icons.aLoveSupremeIcon),
                CategoryCell(title: Strings.mingusAtAntibesTitle,
                             producerTitle: Strings.charlesMingusProducerTitle,
                             cover: Icons.mingusAtAntibesIcon),
                CategoryCell(title: Strings.theCompleteLiveTitle,
                             producerTitle: Strings.leeMorganProducerTitle,
                             cover: Icons.theCompleteIcon)]),
            
            CategorySection(sectionTitle: Strings.legendsOfJazzSectionTitle, cells: [
                CategoryCell(title: Strings.herbieHancockTitle,
                             producerTitle: nil,
                             cover: Icons.herbieCircleIcon),
                CategoryCell(title: Strings.fatsWallerTitle,
                             producerTitle: nil,
                             cover: Icons.fatsCircleIcon),
                CategoryCell(title: Strings.maryLouTitle,
                             producerTitle: Strings.williamsProducerTitle,
                             cover: Icons.maryCircleIcon),
                CategoryCell(title: Strings.ellaFitzgeraldTitle,
                             producerTitle: nil,
                             cover: Icons.ellaCircleIcon),
                CategoryCell(title: Strings.dexterGordonTitle,
                             producerTitle: nil,
                             cover: Icons.dexterCircleIcon),
                CategoryCell(title: Strings.dukeEllingtonTitle,
                             producerTitle: nil,
                             cover: Icons.dukeCircleIcon)]),
            
            CategorySection(sectionTitle: Strings.mainAlbumsSectionTitle, cells: [
                CategoryCell(title: Strings.chetBakerSingsTitle,
                             producerTitle: Strings.chetBakerProducerTitle,
                             cover: Icons.chetBakerSingsIcon),
                CategoryCell(title: Strings.songsForSwinginTitle,
                             producerTitle: Strings.frankSenatraProducerTitle,
                             cover: Icons.songsForSwinginIcon),
                CategoryCell(title: Strings.kindOfBlueTitle,
                             producerTitle: Strings.milesDevisProducerTitle,
                             cover: Icons.kindOfBlueIcon),
                CategoryCell(title: Strings.getzGilbertoTitle,
                             producerTitle: Strings.stanGetzProducerTitle,
                             cover: Icons.getzIcon),
                CategoryCell(title: Strings.nightTrainTitle,
                             producerTitle: Strings.oscarPetersonProducerTitle,
                             cover: Icons.nightTrainIcon),
                CategoryCell(title: Strings.inTheWeeSmallTitle,
                             producerTitle: Strings.frankSenatraProducerTitle,
                             cover: Icons.inTheWeeIcon),
                CategoryCell(title: Strings.timeOutTitle,
                             producerTitle: Strings.theDaveBrubeckQuartetTitle,
                             cover: Icons.timeOutIcon),
                CategoryCell(title: Strings.blackRadioTitle,
                             producerTitle: Strings.robertGlasperExperimentProducerTitle,
                             cover: Icons.blackRadioIcon)]),
            
            CategorySection(sectionTitle: Strings.favoriteArtistsSectionTitle, cells: [
                CategoryCell(title: Strings.domiTitle,
                             producerTitle: Strings.beckProducerTitle,
                             cover: Icons.domiIcon),
                CategoryCell(title: Strings.tigranTitle,
                             producerTitle: Strings.hamasyanProducerTitel,
                             cover: Icons.tigranIcon),
                CategoryCell(title: Strings.jasmineMyraTitle,
                             producerTitle: nil,
                             cover: Icons.jasmineIcon),
                CategoryCell(title: Strings.joelRossProducerTitle,
                             producerTitle: nil,
                             cover: Icons.joelIcon),
                CategoryCell(title: Strings.cecilemcLorinTitle,
                             producerTitle: Strings.salvantProducerTitle,
                             cover: Icons.cecileIcon),
                CategoryCell(title: Strings.immanuelTitle,
                             producerTitle: Strings.wilkinsProducerTitle,
                             cover: Icons.immanuelIcon)]),
            
            CategorySection(sectionTitle: Strings.soonSectionTitle, cells: [
                CategoryCell(title: Strings.forwardThinkerTitle,
                             producerTitle: Strings.numbusSextetProducerTitle,
                             cover: Icons.forwardIcon),
                CategoryCell(title: Strings.markTremoniSingsTitle,
                             producerTitle: Strings.markTremoniProducerTitle,
                             cover: Icons.markIcon),
                CategoryCell(title: Strings.aLotusInTheMudTitle,
                             producerTitle: Strings.yuNishiyamaProducerTitle,
                             cover: Icons.aLotusIcon),
                CategoryCell(title: Strings.aLoveLikeOursTitle,
                             producerTitle: Strings.asIsProducerTitle,
                             cover: Icons.aLoveIcon)])
        ]
    }
}
